# Gzips web/index.html into include/web_ui.h so the firmware can serve it.
# Runs automatically before every PlatformIO build (see extra_scripts in
# platformio.ini); can also be run by hand: python3 tools/embed_web.py
#
# The stroke font from src/stroke_font.h is injected into the page so the
# phone preview draws exactly the same letters as the display.
import gzip
import json
import os
import re


def build_html(root):
    font = {}
    with open(os.path.join(root, "src", "stroke_font.h")) as f:
        for ch, width, strokes in re.findall(r"\{'(\\.|[^'])', (\d+), \"([^\"]*)\"\}", f.read()):
            font[ch.replace("\\", "")] = [int(width), strokes]
    with open(os.path.join(root, "web", "index.html")) as f:
        html = f.read()
    return html.replace("/*FONT*/{}", json.dumps(font, separators=(",", ":")))


try:
    Import("env")  # noqa: F821  (provided by PlatformIO/SCons)
    root = env.subst("$PROJECT_DIR")  # noqa: F821
    standalone = True
except NameError:
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    standalone = __name__ == "__main__"

if standalone:
    dst = os.path.join(root, "include", "web_ui.h")
    data = gzip.compress(build_html(root).encode(), compresslevel=9, mtime=0)

    lines = []
    for i in range(0, len(data), 20):
        lines.append("    " + ", ".join("0x%02x" % b for b in data[i:i + 20]) + ",")

    out = (
        "// Generated by tools/embed_web.py from web/index.html. Do not edit.\n"
        "#pragma once\n"
        "#include <stddef.h>\n"
        "#include <stdint.h>\n\n"
        "static const uint8_t INDEX_HTML_GZ[] = {\n" + "\n".join(lines) + "\n};\n"
        "static const size_t INDEX_HTML_GZ_LEN = sizeof(INDEX_HTML_GZ);\n"
    )

    old = open(dst).read() if os.path.exists(dst) else None
    if out != old:
        with open(dst, "w") as f:
            f.write(out)
        print("embed_web: wrote %s (%d bytes gzipped)" % (dst, len(data)))
