# Gzips web/index.html into include/web_ui.h so the firmware can serve it.
# Runs automatically before every PlatformIO build (see extra_scripts in
# platformio.ini); can also be run by hand: python3 tools/embed_web.py
#
# The stroke font from src/stroke_font.h is injected into the page so the
# phone preview draws exactly the same letters as the display.
import gzip
import json
import os
import re


def build_html(root):
    font = {}
    with open(os.path.join(root, "src", "stroke_font.h")) as f:
        for ch, width, strokes in re.findall(r"\{'(\\.|[^'])', (\d+), \"([^\"]*)\"\}", f.read()):
            font[ch.replace("\\", "")] = [int(width), strokes]
    with open(os.path.join(root, "web", "index.html")) as f:
        html = f.read()
    return html.replace("/*FONT*/{}", json.dumps(font, separators=(",", ":")))


try:
    Import("env")  # noqa: F821  (provided by PlatformIO/SCons)
    root = env.subst("$PROJECT_DIR")  # noqa: F821
    standalone = True
except NameError:
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    standalone = __name__ == "__main__"

def c_array(name, data):
    lines = []
    for i in range(0, len(data), 20):
        lines.append("    " + ", ".join("0x%02x" % b for b in data[i:i + 20]) + ",")
    return ("static const uint8_t %s[] = {\n" % name + "\n".join(lines) + "\n};\n"
            "static const size_t %s_LEN = sizeof(%s);\n" % (name, name))


def gz(data):
    return gzip.compress(data, compresslevel=9, mtime=0)


if standalone:
    dst = os.path.join(root, "include", "web_ui.h")
    hevc = os.path.join(root, "web", "vendor", "hevc")
    page = gz(build_html(root).encode())
    with open(os.path.join(hevc, "hevc-decode.js"), "rb") as f:
        hevc_js = gz(f.read())
    with open(os.path.join(hevc, "hevc-decode.wasm"), "rb") as f:
        hevc_wasm = gz(f.read())

    out = (
        "// Generated by tools/embed_web.py from web/index.html and web/vendor. Do not edit.\n"
        "#pragma once\n"
        "#include <stddef.h>\n"
        "#include <stdint.h>\n\n"
        + c_array("INDEX_HTML_GZ", page)
        + "\n// HEVC decoder for phone videos (web/vendor/hevc, MIT licence)\n"
        + c_array("HEVC_JS_GZ", hevc_js)
        + c_array("HEVC_WASM_GZ", hevc_wasm)
    )

    old = open(dst).read() if os.path.exists(dst) else None
    if out != old:
        with open(dst, "w") as f:
            f.write(out)
        print("embed_web: wrote %s (page %d bytes, decoder %d bytes gzipped)"
              % (dst, len(page), len(hevc_js) + len(hevc_wasm)))
