#!/usr/bin/env python3
"""Generates src/label_font.h: anti-aliased bold capitals for the ring lettering.

    python3 tools/gen_label_font.py [path/to/Bold.ttf]

Uses Liberation Sans Bold (same shapes and widths as Arial / Helvetica Bold)
by default. Each glyph is an 8-bit coverage bitmap LABEL_FONT_H rows tall with
the cap height at LABEL_FONT_CAP pixels; the renderer rotates and scales them
around the ring.
"""
import os
import sys

from PIL import Image, ImageDraw, ImageFont

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FONT = sys.argv[1] if len(sys.argv) > 1 else "/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf"
CHARS = " ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-.!&+'/:#*,?"
CAP = 56     # cap height in pixels
TOP = 3      # rows above the cap height
BOTTOM = 13  # rows below the baseline (Q tail, comma)
SS = 4       # supersampling

# Font size that gives the wanted cap height.
probe = ImageFont.truetype(FONT, 1000)
l, t, r, b = probe.getbbox("H", anchor="ls")
size = 1000 * CAP / (b - t)
font = ImageFont.truetype(FONT, round(size * SS))
height = TOP + CAP + BOTTOM

glyphs, data = [], []
for ch in CHARS:
    adv = font.getlength(ch) / SS
    img = Image.new("L", (int(adv * SS) + 40 * SS, height * SS), 0)
    ImageDraw.Draw(img).text((20 * SS, (TOP + CAP) * SS), ch, font=font, fill=255, anchor="ls")
    img = img.resize((img.width // SS, height), Image.BOX)
    box = img.getbbox()
    if box is None:
        left, w, pixels = 0, 0, b""
    else:
        x0, x1 = box[0], box[2]
        pixels = img.crop((x0, 0, x1, height)).tobytes()
        left, w = x0 - 20, x1 - x0
    glyphs.append((ch, len(data), w, left, round(adv)))
    data.extend(pixels)


def cchar(c):
    return "'\\''" if c == "'" else "'%s'" % c


out = [
    "#pragma once",
    "// Generated by tools/gen_label_font.py from %s. Do not edit." % os.path.basename(FONT),
    "// Bold capitals for the ring lettering: 8-bit coverage, LABEL_FONT_H rows per",
    "// glyph, cap top at row LABEL_FONT_TOP, baseline at LABEL_FONT_TOP + LABEL_FONT_CAP.",
    "#include <stdint.h>",
    "",
    "struct LabelGlyph {",
    "    char c;",
    "    uint32_t offset;  // into LABEL_FONT_BITS",
    "    uint8_t w;        // bitmap width",
    "    int8_t left;      // bitmap x relative to the pen position",
    "    uint8_t advance;",
    "};",
    "",
    "static const int LABEL_FONT_CAP = %d;" % CAP,
    "static const int LABEL_FONT_TOP = %d;" % TOP,
    "static const int LABEL_FONT_H = %d;" % height,
    "",
    "static const LabelGlyph LABEL_GLYPHS[] = {",
]
for ch, off, w, left, adv in glyphs:
    out.append("    {%s, %d, %d, %d, %d}," % (cchar(ch), off, w, left, adv))
out += ["};", "", "static const uint8_t LABEL_FONT_BITS[] = {"]
for i in range(0, len(data), 24):
    out.append("    " + ",".join(str(v) for v in data[i:i + 24]) + ",")
out += [
    "};",
    "",
    "inline const LabelGlyph *labelGlyph(char c) {",
    "    if (c >= 'a' && c <= 'z') c -= 32;",
    "    for (const LabelGlyph &g : LABEL_GLYPHS) {",
    "        if (g.c == c) return &g;",
    "    }",
    "    return &LABEL_GLYPHS[0];  // space",
    "}",
    "",
]
with open(os.path.join(ROOT, "src", "label_font.h"), "w") as f:
    f.write("\n".join(out))
print("%d glyphs, %d bytes" % (len(glyphs), len(data)))
